=== odik8/BSE_2.17/code/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Person",
    "properties": {
        "name": {
            "type": "string"
        },
        "lastname": {
            "type": "string"
        },
        "phone": {
            "type": "string"
        },
        "birthdate": {
            "type": "string"
        }

    },
    "required": ["name", "lastname", "phone", "birthdate"],
    "additionalProperties": false
}

=== odik8/BSE_2.17/code/data.json
[
    {
        "name": "odissey",
        "lastname": "meltonyan",
        "phone": "123123",
        "birthdate": "01.01.1999"
    },
    {
        "name": "igor",
        "lastname": "vikhorkov",
        "phone": "777777",
        "birthdate": "07.07.1977"
    },
    {
        "name": "Yaroslav",
        "lastname": "Mindal",
        "phone": "099099",
        "birthdate": "12.12.2012"
    }
]
